jobs:
  - script: >
      pipelineJob('docker-test') {
        definition {
          cps {
            script('''
              pipeline {
                agent any
                stages {
                  stage('test docker') {
                    steps {
                      sh 'docker ps'
                    }
                  }
                }
              }
            ''')
            sandbox()
          }
        }
      }

  - script: >
      pipelineJob('jenkins-env-automation') {
        description('This job automates Jenkins setup, testing, and environment management.')
        parameters {
          stringParam('SUBDOMAIN', '', 'Specify the subdomain for the Jenkins instance, e.g. "jenkins-instance"')
          stringParam('CONFIG_REPO', '', 'GitHub link to the configuration repository.')
          stringParam('BRANCH', '', 'Branch of the configuration repository to use (optional).')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/cqNikolaus/jenkins_automation')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

  - script: >
      pipelineJob('jenkins-setup') {
        description('This job sets up Jenkins using the Jenkinsfile_setup.')
        parameters {
          stringParam('SUBDOMAIN', '', 'Specify the subdomain for the Jenkins instances, e.g. jenkins-instance')
          stringParam('CONFIG_REPO', '', 'GitHub link to the configuration repository.')
          stringParam('BRANCH', '', 'Branch of the configuration repository to use (optional).')
          stringParam('NUM_INSTANCES', '1', 'Specify the number of Jenkins instances to set up.')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/cqNikolaus/jenkins_automation.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile_Setup')
          }
        }
      }

  - script: >
      pipelineJob('BuildImage') {
        definition {
          cps {
            script('''
              node() {
                git branch: 'main', url: 'https://github.com/cqNikolaus/jenkins_automation.git'
                sh "ls -lart"
                sh "docker build --no-cache -t python-build ."
              }
            ''')
            sandbox()
          }
        }
      }